### ISSUE TITLE
Jura Ena Micro 90

### ISSUE THREAD

**Issue by irqnet** [hn/jura-coffee-machine#1]
Is there any information about compatibility for the Ena Micro 90 model with the 7 pin connector?

I figured out the ports for VCC and GND like shown here - > http://protocoljura.wiki-site.com/index.php/Serial_interfaces

but connecting RX/TX to the specified ports has no reaction while sending a command over the web interface.

**Comment by COM8** [comment]
@irqnet were you able to figure out why nothing happens if you connect to the coffee machine?
I had to change the serial port from `/dev/ttyAMA0` to `/dev/ttyS0` for my RPi3.
Now the coffee maker just replies with what I'm sending to it.
If I connect the coffee maker ground to the RPi ground I'm unable to read anything.

**Comment by DrJeff** [comment]
You may need to use a level shifter for the data lines Jura is using 5V and the Pi is using 3V3 logic for the Data

**Comment by COM8** [comment]
Yes, this fixed it.

**Comment by hn** [comment]
Updated description accordingly
