### ISSUE TITLE
Bad request

### ISSUE THREAD

**Issue by alexswart** [hn/jura-coffee-machine#2]
I have upload this sketch to a nodemcu and it works trough the web interface but curl dont work i got the error bad request

**Comment by andrewerrington** [comment]
What command are you sending? Please post your command line here.

**Comment by alexswart** [comment]
Hello Andrew thank you for your quick response
I do the follow in putty
PI@Raspbery:~$ curl -d 'AN:01' http://192.168.1.30/api

And the response is bad request

**Comment by alexswart** [comment]
If neccesary i can open the port for you for debugging

**Comment by andrewerrington** [comment]
I just tried:
curl -d "TY:" http://192.168.1.103/api
Result:
ty:E70   MASK

You can edit the source code and add some debugging, but it should work.

**Comment by andrewerrington** [comment]
I just tried:
curl -d "TY:" http://192.168.1.103/api
Result:
ty:E70   MASK 3

You could edit the source code and add some debugging, but if should work.

**Comment by alexswart** [comment]
That give me the same result how can i implement some debugging?

**Comment by andrewerrington** [comment]
You got "Bad request"?

I don't know how experienced you are with editing code, but you could change the code to print the data that is "Bad".

You can see the software checks the length of the command. Around line 96. If it's less than 3 then the software responds with a "Bad request" error.

So "TY:" is ok, because it's 3 characters long, but "TY" is not ok because it's only 2 characters.

You could try changing this:
webserver.send(400, "text/plain", "Bad Request");
To this:
webserver.send(400, "text/plain", cmd);

You have to edit the code, compile it, and upload it to your ESP8266 module. Really this should not be necessary. The code works (my coffee machine wakes up automatically every day).

Anyway, if you change the code then instead of "Bad request" you will see the contents of the variable cmd.

So if you send "TY" this is a bad request, so you should see "TY".

If you send "TY:" it should work, but you are saying it doesn't. So, what is printed instead of "Bad request"?

**Comment by andrewerrington** [comment]
If you don't want to change code you could try wget, in case your installation of curl is broken:
wget --post-data 'TY:' http://192.168.1.103/api

**Comment by alexswart** [comment]
I will try tonight change the code.
When i do the wget i get also a bad request response
wget --post-data 'TY:' http://192.168.1.30/api
--2018-10-05 13:56:36--  http://192.168.1.30/api
Connecting to 192.168.1.30:80... connected.
HTTP request sent, awaiting response... 400 Bad Request
2018-10-05 13:56:37 ERROR 400: Bad Request.

**Comment by hn** [comment]
Try curl with '-v' option and compare the result with this:

```
$ curl -v -d 'TY:' http://jura/api
* Hostname was NOT found in DNS cache
*   Trying 192.168.1.103...
* Connected to jura (192.168.1.103) port 80 (#0)
> POST /api HTTP/1.1
> User-Agent: curl
> Host: jura
> Accept: */*
> Content-Length: 3
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 3 out of 3 bytes
< HTTP/1.1 200 OK
< Content-Type: text/plain
< Content-Length: 15
< Connection: close
< Access-Control-Allow-Origin: *
< 
* Closing connection 0
ty:E30   MASK 3
```

**Comment by alexswart** [comment]
This is my log 

pi@domoticz:~$ curl -v -d 'TY:' http://192.168.1.30/api
*   Trying 192.168.1.30...
* TCP_NODELAY set
* Connected to 192.168.1.30 (192.168.1.30) port 80 (#0)
> POST /api HTTP/1.1
> Host: 192.168.1.30
> User-Agent: curl/7.58.0
> Accept: */*
> Content-Length: 3
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 3 out of 3 bytes
< HTTP/1.1 400 Bad Request
< Content-Type: text/plain
< Content-Length: 11
< Connection: close
< 
* Closing connection 0
Bad Requestpi@domoticz:~$

**Comment by alexswart** [comment]
My response is:

pi@domoticz:~$ curl -v -d 'TY:' http://192.168.1.30/api
*   Trying 192.168.1.30...
* TCP_NODELAY set
* Connected to 192.168.1.30 (192.168.1.30) port 80 (#0)
> POST /api HTTP/1.1
> Host: 192.168.1.30
> User-Agent: curl/7.58.0
> Accept: */*
> Content-Length: 3
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 3 out of 3 bytes
< HTTP/1.1 400 Bad Request
< Content-Type: text/plain
< Content-Length: 11
< Connection: close
< 
* Closing connection 0
Bad Request

The only thing that i see what different is is the curl agent

**Comment by alexswart** [comment]
Wich version of arduino and libarys are you using? Maybe there is an problem?

**Comment by hn** [comment]
No info since 14 days, closing issue
